### PR TITLE
Fix Regex in addToken to allow multiline form tag by adding 's' patten modifier

### PR DESCRIPTION
**Pull request by day811**

### CODE REVIEW

**Comment by johanjanssens** [comment]
@ercanozkaya Can you review this.

**Comment by ercanozkaya** [comment]
Hi @day811,
I solved this a bit differently without using the s flag. Can you check the diff here and see if it solves the problem for you:
https://github.com/nooku/nooku-framework/commit/3a7f979af50765860175b4c109bce0168eb1b2dc

**Comment by day811** [comment]
Hi @ercanozkaya,
I was in holidays that why I answer so late.
Anyway, your solution works as well.

**Comment by ercanozkaya** [comment]
@day811 Thanks for testing!

**Pull request closed without merging**
